import type { TwitchSettings } from "$types/platforms/twitch/twitch.settings.types.ts";

export const TWITCH_DEFAULT_SETTINGS: TwitchSettings = {
	chatImagesEnabled: false,
	chatImagesOnHover: false,
	chatImagesSize: 15,
	chatHideGiphyMessages: false,
	chatGiphyMessageMode: "hide",
	chatBadgesEnabled: true,
	chatNicknameCustomizationEnabled: true,
	loadAdditionalFonts: true,
	chatMessageMenuEnabled: true,
	chatMessageMenuUseAddInsteadOfSet: false,
	chatMentionSoundEnabled: false,
	chatMentionSoundSource: "",
	chatMentionSoundFile: "",
	chatMentionSoundVolume: 50,
	pinnedStreamers: [],
	quickAccessLinks: [
		{ title: "TwitchTracker", url: "https://twitchtracker.com/%username%" },
		{ title: "Sullygnome", url: "https://sullygnome.com/channel/%username%" },
		{ title: "Emotes", url: "https://emotes.enhancer.at/?username=%username%" },
	],
	streamLatencyEnabled: true,
	streamLatencyReducerEnabled: false,
	streamLatencyReducerMinRate: 1.05,
	streamLatencyReducerMaxRate: 1.1,
	streamLatencyReducerMinThreshold: 3,
	streamLatencyReducerMaxThreshold: 6,
	realVideoTimeEnabled: true,
	realVideoTimeFormat12h: false,
	pinnedStreamersEnabled: true,
	xayoWatchtimeEnabled: true,
	xayoWatchtimePeriod: "365d",
	channelSection: true,
	chattersEnabled: true,
	hideStories: false,
};
